rootUrl: http://localhost:8080/components/vaadin-login/test/visual/
gridUrl: http://localhost:4444/wd/hub
screenshotsDir: ./test/visual/screens

system:
  plugins:
    polyserve:
      port: 8080
    sauce: true

browsers:
  chrome:
    desiredCapabilities:
      browserName: "chrome"
      version: "66.0"
      platform: "Windows 10"

  firefox:
    desiredCapabilities:
      browserName: "firefox"
      version: "47.0"
      platform: "Windows 10"
